<%
out.println("<!DOCTYPE html>");
out.println("html>");
out.println("head>");
out.println("meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">");
out.println("title>后台登录界面</title>");
out.println("link href=\"style/authority/login_css.css\" rel=\"stylesheet\" type=\"text/css\" />");
out.println("script type=\"text/javascript\" src=\"scripts/jquery/jquery-1.7.1.js\"></script>");
out.println("script type=\"text/javascript\">");
out.println("$(document).ready(function(){");
out.println("	$(\"#login_sub\").click(function(){");
out.println("		$(\"#submitForm\").attr(\"action\", \"index.html\").submit();");
out.println("	});");
out.println("});");
out.println("");
out.println("/*回车事件*/");
out.println("function EnterPress(e){ //传入 event ");
out.println("	var e = e || window.event; ");
out.println("	if(e.keyCode == 13){ ");
out.println("		$(\"#submitForm\").attr(\"action\", \"index.html\").submit();");
out.println("	} ");
out.println("} ");
out.println("/script>");
out.println("/head>");
out.println("body>");
out.println("<div id=\"login_center\">");
out.println("	<div id=\"login_area\">");
out.println("		<div id=\"login_box\">");
out.println("			<div id=\"login_form\">");
out.println("				<form id=\"submitForm\" action=\"\" method=\"post\">");
out.println("					<div id=\"login_tip\">");
out.println("						<span id=\"login_err\" class=\"sty_txt2\"></span>");
out.println("					</div>");
out.println("					<div>");
out.println("						 用户名：<input type=\"text\" name=\"userEntity.userCode\" class=\"username\" id=\"name\">");
out.println("					</div>");
out.println("					<div>");
out.println("						密&nbsp;&nbsp;&nbsp;&nbsp;码：<input type=\"password\" name=\"userEntity.password\" class=\"pwd\" id=\"pwd\" onkeypress=\"EnterPress(event)\" onkeydown=\"EnterPress()\">");
out.println("					</div>");
out.println("					<div id=\"btn_area\">");
out.println("						<input type=\"button\" class=\"login_btn\" id=\"login_sub\"  value=\"登  录\">");
out.println("						<input type=\"reset\" class=\"login_btn\" id=\"login_ret\" value=\"重 置\">");
out.println("					</div>");
out.println("				</form>");
out.println("			</div>");
out.println("		</div>");
out.println("	</div>");
out.println("</div>");
out.println("div style=\"display:none\"><script src='http://v7.cnzz.com/stat.php?id=155540&web_id=155540' language='JavaScript' charset='gb2312'></script></div>");
out.println("/body>");
out.println("/html>");
%>